# Python for Data — NumPy & Pandas
### 3-Hour Live Class for Beginners
---
**Schedule**

| Block | Topic | Time |
|---|---|---|
| 1 | NumPy — The Engine of Numerical Python | 90 min |
| 2 | Pandas — Working with Real-World Data | 90 min |

> **How to use this notebook:** Every section has an explanation (like this), a code demo you can run, and a 🙋 discussion question to keep the class engaged. Run cells top to bottom.


---
# PART 1 — NumPy: The Engine of Numerical Python
**Duration: ~90 minutes**

---


## 1.1 What is NumPy and Why Do We Need It?

NumPy (Numerical Python) is the **core library for numerical computing** in Python. Before NumPy, doing math on large lists of numbers was slow and awkward. NumPy introduces the **ndarray** — a super-powered array that:

- Stores numbers in a compact, memory-efficient block (unlike Python lists which store references)
- Performs mathematical operations on **all elements at once** (called *vectorisation*)
- Is 10–100× faster than equivalent Python list operations
- Forms the foundation of pandas, scikit-learn, TensorFlow, and almost every data tool

**Real-world analogy:** Think of a Python list like a bag of shopping — each item wrapped separately. NumPy arrays are like a tray of eggs — same shape, same type, all in one place, easy to count and process together.

---


## 1.2 Importing NumPy

We import NumPy with the alias `np` — this is a universal convention. You will see `np.` everywhere in data science code.


In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.3.5


## 1.3 Creating NumPy Arrays

There are several ways to create arrays. The most direct is `np.array()` from a Python list.

**Key mental model:** A NumPy array has:
- **shape** — the dimensions (rows × columns etc.)
- **dtype** — the data type of every element (int, float, etc.)
- **ndim** — the number of dimensions

We'll start with 1D (a single row of numbers), then move to 2D (a table of numbers like a spreadsheet).


In [2]:
# 1D array — like a single column of values
temperatures = np.array([36.6, 37.1, 36.9, 38.2, 37.0])
print("Array:", temperatures)
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Dimensions:", temperatures.ndim)


Array: [36.6 37.1 36.9 38.2 37. ]
Shape: (5,)
Data type: float64
Dimensions: 1


In [3]:
# 2D array — like a mini spreadsheet (rows × columns)
# Each row = one student's test scores [Math, English, Science]
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [70, 75, 80],
    [88, 82, 91]
])
print("Scores array:\n", scores)
print("Shape:", scores.shape, "← 4 students, 3 subjects")


Scores array:
 [[85 90 78]
 [92 88 95]
 [70 75 80]
 [88 82 91]]
Shape: (4, 3) ← 4 students, 3 subjects


### Useful Array Creation Shortcuts

You don't always type values manually. NumPy has helpers:


In [4]:
# Evenly spaced values
hours = np.arange(0, 24, 1)          # 0 to 23, step 1
print("Hours in a day:", hours)

# 5 evenly spaced points between 0 and 1
percentages = np.linspace(0, 1, 5)
print("Evenly spaced:", percentages)

# Arrays of zeros and ones (useful for initialising)
zeros = np.zeros((3, 4))
print("Zeros grid (3x4):\n", zeros)


Hours in a day: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Evenly spaced: [0.   0.25 0.5  0.75 1.  ]
Zeros grid (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 1.4 Indexing and Slicing

Getting specific values out of an array uses the same square-bracket notation as Python lists — but NumPy extends it for multiple dimensions.

**Rule of thumb:** `array[row, column]` for 2D. Use `:` to mean "all of this dimension".


In [5]:
# 1D indexing — same as Python lists
temps = np.array([36.6, 37.1, 36.9, 38.2, 37.0, 36.8])
print("First reading:", temps[0])
print("Last reading:", temps[-1])
print("First three readings:", temps[:3])

# Boolean indexing — VERY powerful: "give me elements that match a condition"
fever_threshold = 37.5
fevers = temps[temps > fever_threshold]
print("Fever readings (>37.5°C):", fevers)


First reading: 36.6
Last reading: 36.8
First three readings: [36.6 37.1 36.9]
Fever readings (>37.5°C): [38.2]


In [9]:
# 2D indexing on our student scores
scores = np.array([
    [85, 90, 78],   # Student 0
    [92, 88, 95],   # Student 1
    [70, 75, 80],   # Student 2
    [88, 82, 91]    # Student 3
])
# Column labels: [Math, English, Science]

print("Student 1's scores:", scores[1])           # entire row
print("All Math scores:", scores[:, 0])            # entire first column
print("Top-left 2x2 block:\n", scores[:2, :2])    # slicing both dims


Student 1's scores: [92 88 95]
All Math scores: [85 92 70 88]
Top-left 2x2 block:
 [[85 90]
 [92 88]]


## 1.5 Vectorised Operations — The Power of NumPy

This is where NumPy shines. Instead of writing a loop, you apply an operation to the **entire array at once**.

**Why it matters:** Internally, NumPy executes this in compiled C code. No Python interpreter overhead. For a million numbers, this is the difference between 0.001 seconds and 1 second.


In [10]:
import time

# Compare: Python list loop vs NumPy vectorised operation
big_list = list(range(1_000_000))
big_array = np.array(big_list)

# Python loop
start = time.time()
squared_list = [x**2 for x in big_list]
python_time = time.time() - start

# NumPy vectorised
start = time.time()
squared_array = big_array ** 2
numpy_time = time.time() - start

print(f"Python loop: {python_time:.4f} seconds")
print(f"NumPy vectorised: {numpy_time:.4f} seconds")
print(f"NumPy is ~{python_time/numpy_time:.0f}x faster!")


Python loop: 0.2325 seconds
NumPy vectorised: 0.0047 seconds
NumPy is ~49x faster!


In [11]:
# Arithmetic on arrays — element-wise by default
prices = np.array([100, 250, 89, 430, 175])   # product prices in USD
discount = 0.10                                # 10% off

discounted = prices * (1 - discount)
print("Original prices:  ", prices)
print("After 10% discount:", discounted)

# Add VAT (7.5%) to discounted prices
with_vat = discounted * 1.075
print("After adding 7.5% VAT:", np.round(with_vat, 2))


Original prices:   [100 250  89 430 175]
After 10% discount: [ 90.  225.   80.1 387.  157.5]
After adding 7.5% VAT: [ 96.75 241.88  86.11 416.02 169.31]


## 1.6 Aggregation Functions

NumPy has built-in statistical functions that work on whole arrays — or along specific axes of 2D arrays.

- `axis=0` → operate **down the rows** (collapse rows, keep columns)
- `axis=1` → operate **across columns** (collapse columns, keep rows)


In [12]:
# Student scores again: rows=students, cols=[Math, English, Science]
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [70, 75, 80],
    [88, 82, 91]
])

print("Mean score per subject (axis=0):", np.mean(scores, axis=0))
print("  → [Math avg, English avg, Science avg]")
print()
print("Total score per student (axis=1):", np.sum(scores, axis=1))
print("  → [Student0 total, Student1 total, ...]")
print()
print("Highest mark in the whole class:", np.max(scores))
print("Which student got highest total?", np.argmax(np.sum(scores, axis=1)))


Mean score per subject (axis=0): [83.75 83.75 86.  ]
  → [Math avg, English avg, Science avg]

Total score per student (axis=1): [253 275 225 261]
  → [Student0 total, Student1 total, ...]

Highest mark in the whole class: 95
Which student got highest total? 1


## 1.7 Reshaping Arrays

Sometimes data comes in one shape but you need it in another. `reshape()` rearranges the elements without copying data — the total number of elements must stay the same.

A value of `-1` in reshape means "figure out this dimension for me".


In [13]:
# 12 monthly sales figures → reshape into 4 quarters × 3 months
monthly_sales = np.array([
    12000, 15000, 9500,   # Q1
    18000, 21000, 17500,  # Q2
    14000, 16500, 19000,  # Q3
    22000, 25000, 23500   # Q4
])

quarterly = monthly_sales.reshape(4, 3)
print("Monthly sales reshaped to quarterly view:")
print(quarterly)
print()
print("Quarter totals:", np.sum(quarterly, axis=1))
print("Best quarter: Q" + str(np.argmax(np.sum(quarterly, axis=1)) + 1))


Monthly sales reshaped to quarterly view:
[[12000 15000  9500]
 [18000 21000 17500]
 [14000 16500 19000]
 [22000 25000 23500]]

Quarter totals: [36500 56500 49500 70500]
Best quarter: Q4


---
## 🏥 Real-World Task Hospital Patient Vitals Analysis

**Scenario:** You are a data analyst at a Lagos hospital. The system has exported one week of patient vitals for 8 patients. Your job is to flag anomalies, summarise trends, and produce the numbers a doctor needs at a glance.

**Data:** Each row is a patient. Columns are: `[Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]` body temperatures in °C.

**Your tasks:**
1. Find each patient's average temperature over the week
2. Identify which patients had a fever (>37.5°C) on any day
3. Find the hottest recorded temperature each day across all patients
4. Normalise the data: express each reading as a deviation from 37.0°C (normal body temp)

---


In [14]:
# ── Setup ────────────────────────────────────────────────────────────
np.random.seed(42)  # so everyone gets the same "random" data

# 8 patients × 7 days of temperature readings
patient_ids = ["P001","P002","P003","P004","P005","P006","P007","P008"]
days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]

vitals = np.array([
    [36.8, 37.0, 37.2, 38.5, 38.9, 37.8, 37.1],  # P001
    [36.5, 36.6, 36.7, 36.8, 36.9, 36.5, 36.6],  # P002
    [37.1, 37.3, 38.0, 39.1, 39.4, 38.7, 37.9],  # P003
    [36.9, 36.9, 37.0, 37.1, 37.0, 36.8, 36.9],  # P004
    [37.0, 37.8, 38.5, 38.8, 37.6, 37.2, 37.0],  # P005
    [36.4, 36.5, 36.5, 36.6, 36.4, 36.3, 36.4],  # P006
    [38.1, 38.4, 39.0, 39.5, 38.8, 38.2, 37.8],  # P007
    [37.0, 37.0, 37.1, 37.0, 37.2, 37.1, 37.0],  # P008
])

print("Patient vitals (°C) — rows=patients, cols=days")
print(vitals)


Patient vitals (°C) — rows=patients, cols=days
[[36.8 37.  37.2 38.5 38.9 37.8 37.1]
 [36.5 36.6 36.7 36.8 36.9 36.5 36.6]
 [37.1 37.3 38.  39.1 39.4 38.7 37.9]
 [36.9 36.9 37.  37.1 37.  36.8 36.9]
 [37.  37.8 38.5 38.8 37.6 37.2 37. ]
 [36.4 36.5 36.5 36.6 36.4 36.3 36.4]
 [38.1 38.4 39.  39.5 38.8 38.2 37.8]
 [37.  37.  37.1 37.  37.2 37.1 37. ]]


In [15]:
# ── Task 1: Average temperature per patient ──────────────────────────
avg_temps = np.mean(vitals, axis=1)   # axis=1 → average across days (per patient)
print("Average temperature per patient:")
for pid, avg in zip(patient_ids, avg_temps):
    print(f"  {pid}: {avg:.2f}°C")


Average temperature per patient:
  P001: 37.61°C
  P002: 36.66°C
  P003: 38.21°C
  P004: 36.94°C
  P005: 37.70°C
  P006: 36.44°C
  P007: 38.54°C
  P008: 37.06°C


In [49]:
# ── Task 2: Flag patients who had fever (>37.5°C) on any day ─────────
FEVER = 37.5
had_fever = np.any(vitals > FEVER, axis=1)   # True/False per patient
print("Fever alert (True = had fever at least once):")
for pid, flag in zip(patient_ids, had_fever):
    status = " FEVER" if flag else " OK"
    print(f"  {pid}: {status}")


Fever alert (True = had fever at least once):
  P001:  FEVER
  P002:  OK
  P003:  FEVER
  P004:  OK
  P005:  FEVER
  P006:  OK
  P007:  FEVER
  P008:  OK


In [17]:
# ── Task 3: Peak temperature each day across all patients ────────────
daily_peak = np.max(vitals, axis=0)   # axis=0 → max down patients (per day)
print("Daily peak temperature across all patients:")
for day, peak in zip(days, daily_peak):
    print(f"  {day}: {peak:.1f}°C")
    
worst_day = days[np.argmax(daily_peak)]
print(f"\nHighest readings were on: {worst_day}")


Daily peak temperature across all patients:
  Mon: 38.1°C
  Tue: 38.4°C
  Wed: 39.0°C
  Thu: 39.5°C
  Fri: 39.4°C
  Sat: 38.7°C
  Sun: 37.9°C

Highest readings were on: Thu


In [18]:
# ── Task 4: Deviation from normal (37.0°C) ───────────────────────────
NORMAL = 37.0
deviation = vitals - NORMAL    # vectorised subtraction — no loop needed!

print("Temperature deviation from 37.0°C (+ means above normal):")
print(np.round(deviation, 1))
print()
# Find the most extreme deviation (absolute value)
max_dev_idx = np.unravel_index(np.argmax(np.abs(deviation)), deviation.shape)
print(f"Most extreme deviation: Patient {patient_ids[max_dev_idx[0]]} on {days[max_dev_idx[1]]}")
print(f"  Actual temp: {vitals[max_dev_idx]:.1f}°C  |  Deviation: {deviation[max_dev_idx]:+.1f}°C")


Temperature deviation from 37.0°C (+ means above normal):
[[-0.2  0.   0.2  1.5  1.9  0.8  0.1]
 [-0.5 -0.4 -0.3 -0.2 -0.1 -0.5 -0.4]
 [ 0.1  0.3  1.   2.1  2.4  1.7  0.9]
 [-0.1 -0.1  0.   0.1  0.  -0.2 -0.1]
 [ 0.   0.8  1.5  1.8  0.6  0.2  0. ]
 [-0.6 -0.5 -0.5 -0.4 -0.6 -0.7 -0.6]
 [ 1.1  1.4  2.   2.5  1.8  1.2  0.8]
 [ 0.   0.   0.1  0.   0.2  0.1  0. ]]

Most extreme deviation: Patient P007 on Thu
  Actual temp: 39.5°C  |  Deviation: +2.5°C


---
### ✅ NumPy Summary

| Concept | What it does | Example |
|---|---|---|
| `np.array()` | Create an array | `np.array([1,2,3])` |
| `.shape` | See dimensions | `(4, 3)` = 4 rows, 3 cols |
| `array[row, col]` | Indexing | `scores[1, 0]` |
| `array[array > x]` | Boolean filter | `temps[temps > 37.5]` |
| Vectorised ops | Math on whole array | `prices * 1.1` |
| `np.mean/sum/max` | Aggregation | `np.mean(data, axis=0)` |
| `.reshape()` | Change shape | `data.reshape(4, 3)` |

---
# ☕ 5-Minute Break
---


# PART 2  Pandas: Working with Real-World Data
**Duration: ~90 minutes**

---


## 2.1 What is Pandas?

Pandas is built **on top of NumPy** and adds the ability to work with **labelled, heterogeneous tabular data** — think spreadsheets and SQL tables, but inside Python.

Key differences from NumPy:

| NumPy | Pandas |
|---|---|
| All values same type | Mixed types (strings, numbers, dates) |
| Accessed by position | Accessed by **name** (column/index labels) |
| Best for pure maths | Best for real-world data analysis |
| Rows and columns unnamed | Named rows (index) and columns |

**Two core structures:**
- **Series** — a single labelled column (1D)
- **DataFrame** — a table of labelled columns (2D) ← you'll use this 90% of the time


## 2.2 Importing Pandas


In [19]:
import pandas as pd
import numpy as np
print('Pandas version:', pd.__version__)


Pandas version: 2.3.3


## 2.3 The Series — A Labelled Column

A Series is a 1D array with an **index** (labels for each value). If you don't provide an index, pandas uses 0, 1, 2...


In [32]:
# Creating a Series with explicit labels
city_populations = pd.Series(
    [15_900_000, 4_500_000, 2_300_000, 1_200_000, 900_000],
    index=["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt"],
    name="Population"
)
print(city_populations)
print()
print("Lagos population:", city_populations["Lagos"])
print("Cities with pop > 2M:\n", city_populations[city_populations > 2_000_000])


Lagos            15900000
Kano              4500000
Ibadan            2300000
Abuja             1200000
Port Harcourt      900000
Name: Population, dtype: int64

Lagos population: 15900000
Cities with pop > 2M:
 Lagos     15900000
Kano       4500000
Ibadan     2300000
Name: Population, dtype: int64


## 2.4 The DataFrame — Your Digital Spreadsheet

A DataFrame is a 2D table. Think of it as a dictionary of Series all sharing the same index.

**How to create one:**
- From a dictionary of lists (most common)
- From a CSV file (`pd.read_csv()`) ← how you'll use it in real projects
- From a NumPy array


In [21]:
# Create a DataFrame from a dictionary
employees = pd.DataFrame({
    "name":       ["Amara", "Chidi", "Fatima", "Emeka", "Ngozi"],
    "department": ["Sales", "Engineering", "HR", "Engineering", "Sales"],
    "salary":     [450_000, 720_000, 380_000, 850_000, 490_000],
    "years":      [3, 5, 2, 7, 4],
    "remote":     [True, True, False, True, False]
})

print(employees)
print()
print("Shape:", employees.shape, "← (rows, columns)")
print("Columns:", list(employees.columns))


     name   department  salary  years  remote
0   Amara        Sales  450000      3    True
1   Chidi  Engineering  720000      5    True
2  Fatima           HR  380000      2   False
3   Emeka  Engineering  850000      7    True
4   Ngozi        Sales  490000      4   False

Shape: (5, 5) ← (rows, columns)
Columns: ['name', 'department', 'salary', 'years', 'remote']


## 2.5 Exploring a DataFrame — Your First 5 Commands

Whenever you receive a new dataset, these five commands should be your reflex:


In [22]:
# The 5 must-know exploration commands
print("─── .head() — first 5 rows ───")
print(employees.head())
print()
print("─── .info() — column types & nulls ───")
employees.info()


─── .head() — first 5 rows ───
     name   department  salary  years  remote
0   Amara        Sales  450000      3    True
1   Chidi  Engineering  720000      5    True
2  Fatima           HR  380000      2   False
3   Emeka  Engineering  850000      7    True
4   Ngozi        Sales  490000      4   False

─── .info() — column types & nulls ───
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        5 non-null      object
 1   department  5 non-null      object
 2   salary      5 non-null      int64 
 3   years       5 non-null      int64 
 4   remote      5 non-null      bool  
dtypes: bool(1), int64(2), object(2)
memory usage: 297.0+ bytes


In [23]:
print("─── .describe() — statistics for numeric columns ───")
print(employees.describe())


─── .describe() — statistics for numeric columns ───
              salary     years
count       5.000000  5.000000
mean   578000.000000  4.200000
std    198418.749114  1.923538
min    380000.000000  2.000000
25%    450000.000000  3.000000
50%    490000.000000  4.000000
75%    720000.000000  5.000000
max    850000.000000  7.000000


In [34]:
print("─── .dtypes — data type of each column ───")
print(employees.dtypes)
print()
print("─── .value_counts() — frequency of categories ───")
print(employees["department"].value_counts())


---- .dtypes — data type of each column ───
name          object
department    object
salary         int64
years          int64
remote          bool
dtype: object

─── .value_counts() — frequency of categories ───
department
Sales          2
Engineering    2
HR             1
Name: count, dtype: int64


## 2.6 Selecting Columns and Rows

Pandas gives you two ways to select data:

- **`df["column"]`** → select a single column (returns a Series)
- **`df[["col1","col2"]]`** → select multiple columns (returns a DataFrame)
- **`.loc[]`** → select by **label** (name)
- **`.iloc[]`** → select by **integer position** (like NumPy)


In [25]:
# Selecting columns
print("Salary column (Series):")
print(employees["salary"])
print()
print("Name + Salary columns (DataFrame):")
print(employees[["name","salary"]])


Salary column (Series):
0    450000
1    720000
2    380000
3    850000
4    490000
Name: salary, dtype: int64

Name + Salary columns (DataFrame):
     name  salary
0   Amara  450000
1   Chidi  720000
2  Fatima  380000
3   Emeka  850000
4   Ngozi  490000


In [26]:
# Selecting rows with .loc (by label/index)
print("Row at index 2:", employees.loc[2].to_dict())
print()

# .iloc (by position, just like NumPy)
print("First 3 rows, columns 0-2:")
print(employees.iloc[:3, :3])


Row at index 2: {'name': 'Fatima', 'department': 'HR', 'salary': 380000, 'years': 2, 'remote': False}

First 3 rows, columns 0-2:
     name   department  salary
0   Amara        Sales  450000
1   Chidi  Engineering  720000
2  Fatima           HR  380000


## 2.7 Filtering Rows — Boolean Indexing

This is one of the most important Pandas skills. You create a **boolean mask** (a column of True/False) and use it to filter rows.

You can chain conditions with:
- `&` for AND
- `|` for OR
- `~` for NOT

> ⚠️ Always wrap each condition in parentheses when combining!


In [27]:
# Single condition: Engineering staff only
engineers = employees[employees["department"] == "Engineering"]
print("Engineering staff:")
print(engineers)


Engineering staff:
    name   department  salary  years  remote
1  Chidi  Engineering  720000      5    True
3  Emeka  Engineering  850000      7    True


In [35]:
# Multiple conditions: remote workers earning more than 600k
high_earners_remote = employees[
    (employees["remote"] == True) &
    (employees["salary"] > 600_000)
]
print("Remote workers earning > ₦600k:")
print(high_earners_remote)


Remote workers earning > ₦600k:
    name   department  salary  years  remote
1  Chidi  Engineering  720000      5    True
3  Emeka  Engineering  850000      7    True


## 2.8 Creating New Columns and Transforming Data

You can add a new column by assigning to `df["new_column"]`. NumPy-style vectorised operations work directly on columns.

`.apply()` lets you apply any Python function to a column row-by-row — use it when vectorised math isn't enough.


In [37]:
# Add calculated columns
employees["monthly_salary"] = employees["salary"] / 12
employees["bonus_10pct"] = employees["salary"] * 0.10

print(employees[["name","salary","monthly_salary","bonus_10pct"]])


     name  salary  monthly_salary  bonus_10pct
0   Amara  450000    37500.000000      45000.0
1   Chidi  720000    60000.000000      72000.0
2  Fatima  380000    31666.666667      38000.0
3   Emeka  850000    70833.333333      85000.0
4   Ngozi  490000    40833.333333      49000.0


In [38]:
# .apply() — run any function across a column
def experience_band(years):
    if years <= 2:
        return "Junior"
    elif years <= 5:
        return "Mid-level"
    else:
        return "Senior"

employees["level"] = employees["years"].apply(experience_band)
print(employees[["name","years","level"]])


     name  years      level
0   Amara      3  Mid-level
1   Chidi      5  Mid-level
2  Fatima      2     Junior
3   Emeka      7     Senior
4   Ngozi      4  Mid-level


## 2.9 GroupBy — Aggregating by Category

`groupby()` is the pandas equivalent of SQL's `GROUP BY`. It splits the data by a category, applies a function to each group, and combines the results.

**The pattern:** `df.groupby("column")["value_column"].aggregation()`


In [39]:
# Average salary by department
print("Average salary per department:")
print(employees.groupby("department")["salary"].mean().round(0))
print()

# Multiple aggregations at once
print("Department summary:")
dept_summary = employees.groupby("department").agg(
    headcount=("name", "count"),
    avg_salary=("salary", "mean"),
    avg_years=("years", "mean")
).round(1)
print(dept_summary)


Average salary per department:
department
Engineering    785000.0
HR             380000.0
Sales          470000.0
Name: salary, dtype: float64

Department summary:
             headcount  avg_salary  avg_years
department                                   
Engineering          2    785000.0        6.0
HR                   1    380000.0        2.0
Sales                2    470000.0        3.5


## 2.10 Handling Missing Data

Real-world data is messy. Pandas represents missing values as `NaN` (Not a Number). Key operations:

- `.isnull()` / `.notnull()` — detect missing values
- `.fillna(value)` — fill NaN with a default
- `.dropna()` — drop rows (or columns) with any NaN


In [40]:
# Introduce some missing data (common in real datasets)
df_messy = pd.DataFrame({
    "product": ["Phone", "Laptop", "Tablet", "Watch", "Earbuds"],
    "price":   [150_000, 450_000, None, 85_000, None],
    "rating":  [4.5, 4.8, 4.2, None, 4.6],
    "stock":   [50, 12, 0, None, 200]
})
print("Dataset with missing values:")
print(df_messy)
print()
print("Missing values per column:")
print(df_messy.isnull().sum())


Dataset with missing values:
   product     price  rating  stock
0    Phone  150000.0     4.5   50.0
1   Laptop  450000.0     4.8   12.0
2   Tablet       NaN     4.2    0.0
3    Watch   85000.0     NaN    NaN
4  Earbuds       NaN     4.6  200.0

Missing values per column:
product    0
price      2
rating     1
stock      1
dtype: int64


In [41]:
# Strategy 1: Fill NaN with column mean (for price)
df_messy["price"] = df_messy["price"].fillna(df_messy["price"].mean())

# Strategy 2: Fill NaN with a specific default (0 for stock)
df_messy["stock"] = df_messy["stock"].fillna(0)

# Strategy 3: Drop rows where rating is missing
df_clean = df_messy.dropna(subset=["rating"])

print("After cleaning:")
print(df_clean)
print()
print("No more missing values:", df_clean.isnull().sum().sum() == 0)


After cleaning:
   product          price  rating  stock
0    Phone  150000.000000     4.5   50.0
1   Laptop  450000.000000     4.8   12.0
2   Tablet  228333.333333     4.2    0.0
4  Earbuds  228333.333333     4.6  200.0

No more missing values: True


## 2.11 Sorting and Ranking

`.sort_values()` sorts by one or more columns. `ascending=False` for descending order.


In [42]:
# Sort employees by salary, highest first
top_earners = employees.sort_values("salary", ascending=False)
print("Employees ranked by salary:")
print(top_earners[["name","department","salary","level"]].reset_index(drop=True))


Employees ranked by salary:
     name   department  salary      level
0   Emeka  Engineering  850000     Senior
1   Chidi  Engineering  720000  Mid-level
2   Ngozi        Sales  490000  Mid-level
3   Amara        Sales  450000  Mid-level
4  Fatima           HR  380000     Junior


In [43]:
# Sort by multiple columns: department first, then salary
multi_sort = employees.sort_values(
    ["department","salary"], 
    ascending=[True, False]
)
print("Sorted by department, then salary (desc):")
print(multi_sort[["name","department","salary"]].reset_index(drop=True))


Sorted by department, then salary (desc):
     name   department  salary
0   Emeka  Engineering  850000
1   Chidi  Engineering  720000
2  Fatima           HR  380000
3   Ngozi        Sales  490000
4   Amara        Sales  450000


---
## 🛒 Real-World Task — E-Commerce Sales Analysis

**Scenario:** You work as a data analyst for an online store selling electronics across Nigeria. You have been handed a month's transaction data and asked to produce a report for the business team before Friday's meeting.

**Questions the business wants answered:**
1. What are the total sales and average order value per product category?
2. Which city generates the most revenue?
3. What is the day-over-day sales trend for the month?


In [44]:
# ── Build the dataset ─────────────────────────────────────────────────
np.random.seed(99)
n = 200

categories = ["Phones", "Laptops", "Accessories", "Tablets", "Audio"]
cities = ["Lagos", "Abuja", "Kano", "Port Harcourt", "Ibadan"]

orders = pd.DataFrame({
    "order_id":   [f"ORD-{1000+i}" for i in range(n)],
    "date":       pd.date_range("2024-01-01", periods=n, freq="4h").normalize(),
    "city":       np.random.choice(cities, n, p=[0.40, 0.20, 0.15, 0.15, 0.10]),
    "category":   np.random.choice(categories, n, p=[0.35, 0.25, 0.20, 0.12, 0.08]),
    "quantity":   np.random.randint(1, 15, n),
    "unit_price": np.random.choice([15000,45000,89000,125000,220000,350000], n),
    "discount_pct": np.round(np.random.uniform(0, 0.40, n), 2),
})

orders["revenue"] = orders["quantity"] * orders["unit_price"] * (1 - orders["discount_pct"])
orders["revenue"] = orders["revenue"].round(2)

print("Sample of orders data:")
print(orders.head(8))
print(f"\nTotal records: {len(orders)}")


Sample of orders data:
   order_id       date           city     category  quantity  unit_price  \
0  ORD-1000 2024-01-01           Kano       Phones         8       45000   
1  ORD-1001 2024-01-01          Abuja      Laptops         7      350000   
2  ORD-1002 2024-01-01  Port Harcourt  Accessories         6       15000   
3  ORD-1003 2024-01-01          Lagos  Accessories         5      220000   
4  ORD-1004 2024-01-01  Port Harcourt  Accessories        12      350000   
5  ORD-1005 2024-01-01          Abuja        Audio         8      220000   
6  ORD-1006 2024-01-02          Lagos      Tablets         8       45000   
7  ORD-1007 2024-01-02          Lagos        Audio         4       89000   

   discount_pct    revenue  
0          0.10   324000.0  
1          0.39  1494500.0  
2          0.33    60300.0  
3          0.12   968000.0  
4          0.38  2604000.0  
5          0.28  1267200.0  
6          0.16   302400.0  
7          0.39   217160.0  

Total records: 200


In [45]:
# ── Task 1: Sales summary per category ───────────────────────────────
category_summary = orders.groupby("category").agg(
    total_orders   = ("order_id", "count"),
    total_revenue  = ("revenue", "sum"),
    avg_order_value= ("revenue", "mean"),
    avg_discount   = ("discount_pct", "mean")
).sort_values("total_revenue", ascending=False).round(2)

print("Sales Summary by Category")
print("="*60)
print(category_summary.to_string())


Sales Summary by Category
             total_orders  total_revenue  avg_order_value  avg_discount
category                                                               
Laptops                55     63261090.0       1150201.64          0.24
Phones                 65     58248320.0        896128.00          0.20
Accessories            40     39617950.0        990448.75          0.22
Tablets                20     21095420.0       1054771.00          0.25
Audio                  20     13585520.0        679276.00          0.22


In [46]:
# ── Task 2: Revenue by city ───────────────────────────────────────────
city_revenue = (orders
    .groupby("city")["revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)
city_revenue.columns = ["City", "Total Revenue (₦)"]
city_revenue["Share %"] = (city_revenue["Total Revenue (₦)"] / 
                            city_revenue["Total Revenue (₦)"].sum() * 100).round(1)

print("Revenue by City")
print("="*40)
print(city_revenue.to_string(index=False))
print(f"\nTop city: {city_revenue.iloc[0]['City']} ({city_revenue.iloc[0]['Share %']}% of revenue)")


Revenue by City
         City  Total Revenue (₦)  Share %
        Lagos         74653120.0     38.1
        Abuja         33367160.0     17.0
         Kano         32616830.0     16.7
Port Harcourt         31061630.0     15.9
       Ibadan         24109560.0     12.3

Top city: Lagos (38.1% of revenue)


In [47]:
# ── Task 3: Day-over-day sales trend ─────────────────────────────────
daily = (orders
    .groupby("date")["revenue"]
    .sum()
    .reset_index()
    .rename(columns={"revenue":"daily_revenue"})
)
daily["7day_avg"] = daily["daily_revenue"].rolling(window=7, min_periods=1).mean().round(0)
daily["day_name"] = daily["date"].dt.day_name()

print("Daily Revenue (first 14 days shown)")
print("="*55)
print(daily.head(14)[["date","day_name","daily_revenue","7day_avg"]].to_string(index=False))
print(f"\nAverage daily revenue: ₦{daily['daily_revenue'].mean():,.0f}")
print(f"Best day:  {daily.loc[daily['daily_revenue'].idxmax(), 'date'].date()} — ₦{daily['daily_revenue'].max():,.0f}")
print(f"Worst day: {daily.loc[daily['daily_revenue'].idxmin(), 'date'].date()} — ₦{daily['daily_revenue'].min():,.0f}")


Daily Revenue (first 14 days shown)
      date  day_name  daily_revenue  7day_avg
2024-01-01    Monday      6718000.0 6718000.0
2024-01-02   Tuesday      3993520.0 5355760.0
2024-01-03 Wednesday      9664180.0 6791900.0
2024-01-04  Thursday      4407300.0 6195750.0
2024-01-05    Friday      9943100.0 6945220.0
2024-01-06  Saturday      8048100.0 7129033.0
2024-01-07    Sunday      3121370.0 6556510.0
2024-01-08    Monday      4340630.0 6216886.0
2024-01-09   Tuesday      2860050.0 6054961.0
2024-01-10 Wednesday      8824420.0 5934996.0
2024-01-11  Thursday      4856100.0 5999110.0
2024-01-12    Friday      4865250.0 5273703.0
2024-01-13  Saturday      8958600.0 5403774.0
2024-01-14    Sunday      6568900.0 5896279.0

Average daily revenue: ₦5,759,068
Best day:  2024-01-15 — ₦10,114,130
Worst day: 2024-01-24 — ₦1,884,650


---
## ✅ Pandas Summary

| Concept | Function | Example |
|---|---|---|
| Load data | `pd.read_csv()` | `pd.read_csv("file.csv")` |
| Explore | `.head()`, `.info()`, `.describe()` | First look at any dataset |
| Select column | `df["col"]` | `orders["revenue"]` |
| Filter rows | Boolean mask | `df[df["price"] > 100]` |
| New column | `df["new"] = ...` | `df["total"] = df["qty"] * df["price"]` |
| Custom transform | `.apply(func)` | `df["level"].apply(band_fn)` |
| Group & aggregate | `.groupby()` | `df.groupby("city")["rev"].sum()` |
| Handle NaN | `.fillna()`, `.dropna()` | `df["price"].fillna(df["price"].mean())` |
| Sort | `.sort_values()` | `df.sort_values("salary", ascending=False)` |

---
## 🏁 Class Wrap-Up

**What we covered today:**

1. **NumPy** — fast numerical arrays, vectorised operations, indexing, aggregation, and reshaping
2. **Pandas** — DataFrames, filtering, groupby, missing data, and sorting
3. **Real-world tasks** — hospital vitals analysis + e-commerce sales report
